namespace Defra.PhaImportNotifications.Contracts
{
    public enum AccompanyingDocumentDocumentTypeEnum
    {
        AirWaybill,
        BillOfLading,
        CargoManifest,
        CatchCertificate,
        CommercialDocument,
        CommercialInvoice,
        ConformityCertificate,
        ContainerManifest,
        CustomsDeclaration,
        Docom,
        HealthCertificate,
        HeatTreatmentCertificate,
        ImportPermit,
        InspectionCertificate,
        Itahc,
        JourneyLog,
        LaboratorySamplingResultsForAflatoxin,
        LatestVeterinaryHealthCertificate,
        LetterOfAuthority,
        LicenseOrAuthorisation,
        MycotoxinCertification,
        OriginCertificate,
        Other,
        PhytosanitaryCertificate,
        ProcessingStatement,
        ProofOfStorage,
        RailwayBill,
        SeaWaybill,
        VeterinaryHealthCertificate,
        ListOfIngredients,
        PackingList,
        RoadConsignmentNote
    }
}
