#nullable enable
using System.Text.Json.Serialization;
using System.ComponentModel;

namespace Defra.PhaImportNotifications.Contracts;
public class EconomicOperator
{
    [JsonPropertyName("id")]
    [Description("The unique identifier of this organisation")]
    public string? Id { get; set; }

    [JsonPropertyName("type")]
    public EconomicOperatorTypeEnum Type { get; set; }

    [JsonPropertyName("status")]
    public EconomicOperatorStatusEnum Status { get; set; }

    [JsonPropertyName("companyName")]
    [Description("Name of organisation")]
    public string? CompanyName { get; set; }

    [JsonPropertyName("individualName")]
    [Description("Individual name")]
    public string? IndividualName { get; set; }

    [JsonPropertyName("address")]
    public Address Address { get; set; }

    [JsonPropertyName("approvalNumber")]
    [Description("Approval Number which identifies an Economic Operator unambiguously per type of organisation per country.")]
    public string? ApprovalNumber { get; set; }

    [JsonPropertyName("otherIdentifier")]
    [Description("Optional Business General Number, often named Aggregation Code, which identifies an Economic Operator.")]
    public string? OtherIdentifier { get; set; }

    [JsonPropertyName("tracesId")]
    [Description("Traces Id of the economic operator generated by IPAFFS")]
    public int? TracesId { get; set; }
}
